#!/bin/bash
set -e

usage() {
  echo "Usage: $0 [all|consul|vault|app] COMMAND ARGS"
  exit 1
}

cmd=
target="$1"

if [ -z $target ]; then
  usage
fi

if [ $target != "consul" ] && [ $target != "vault" ] && [ $target != "app" ]; then
  target="all"
  echo "Using target \"all\""
else
  shift
fi

if [ $target == "all" ]; then
  target="-f consul.yml -f vault.yml -f app.yml"
else
  target="-f ${target}.yml"
fi

cmd="$1"
if [ -z "$cmd" ]; then
  usage
elif [ "$1" == "up" ]; then
  cmd="up -d"
elif [ "$1" == "down" ]; then
  cmd='down -v'
fi
shift

docker-compose -f docker-compose.yml $target $cmd $@
