<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<?php if (!empty($isDbConnected)): ?>
    <div class="alert alert-success" role="alert">
        <strong>Success!</strong> Connection to MySQL server established!
    </div>
    <?php if (!empty($message)): ?>
        <div class="alert alert-success" role="alert">
            <strong>Message from the DB:</strong> <?= $this->e($message) ?>
        </div>
    <?php endif ?>
<?php else: ?>
    <div class="alert alert-danger" role="alert"><strong>Error:</strong> Could not connect to MySQL server!</div>
<?php endif ?>

<div class="jumbotron">
    <h1>Hello <span class="zf-green">PHP Limburg</span>!</h1>
    <p>
        Congratulations! You have successfully installed the application</a>.
        You should see some messages above this text that will indicate the status of the system.
    </p>
    <p>
        Made with love by <a href="https://somoza.be" target="_blank">Gabriel Somoza</a> (
        <a href="https://twitter.com/gabriel_somoza" target="_blank">@gabriel_somoza</a>)
    </p>
</div>
